# prometheus/prometheus.yml
global:
  scrape_interval: 3s
  scrape_timeout: 2s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'wsl_monitor'
    metrics_path: /metrics
    static_configs:
      - targets: ['backend:8000']
